import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { semanticHash } from '../../packages/canonicalization/src/index.mjs';
import {
  AGRONOMIC_POLICY_REQUIRED_KNOWLEDGE_USE,
  AGRONOMIC_RULE_CONTRACT_VERSION_V2,
  agronomicModelDefinitionHash,
  declarativeAgronomicRuleHash,
  publishAgronomicPolicyCompilation,
  validateAgronomicPolicyCompilationAuthority
} from '../../packages/agronomic-policy-compilation/src/index.mjs';
import {
  authorizeKnowledgeInspection,
  authorizeKnowledgeQualification,
  createPrincipal,
  publishBuiltinRoleAssignment,
  publishKnowledgeGovernancePolicy,
  recordAuthorizationDecision
} from '../../packages/authorization/src/index.mjs';
import {
  SOURCE_CONTEXT_FAMILIES,
  ScientificCompiler,
  createDeterministicCompilerDefinition
} from '../../packages/scientific-compiler/src/index.mjs';
import {
  ScientificQualificationService,
  qualificationResourceId
} from '../../packages/knowledge-registry/src/qualification.mjs';
import {
  SourceFaithfulReviewService,
  sourceReviewResourceId
} from '../../packages/knowledge-registry/src/source-faithful.mjs';
import {
  ExactArtifactStore,
  SourceRegistry,
  sourceContentHash
} from '../../packages/source-registry/src/index.mjs';
import { validateSpecificationAuthority } from '../../packages/specification-registry/src/index.mjs';
import {
  audit,
  makeEnv,
  manager,
  modelSpec,
  policySpec,
  publish
} from '../specification/fixture.mjs';

const OWNERSHIP = { organizationId: 'org-a', tenantId: 'tenant-a' };
const PDF_PAGE = 23;
const EXPECTED_TRANSCRIPTION_HASH = 'sha256:8d18c0fcc5a2b536d675e9b1cdafc16fbeedb19204b67c11ae81f887844f71d9';
const SOURCE_LOCATOR = 'current_agronomic_protocol.pdf#page=23';

function locator(evidenceText) {
  return {
    kind: 'DOCUMENT_COORDINATE',
    scheme: 'PDF_PAGE_TEXT_V1',
    coordinates: { page: PDF_PAGE, evidenceText }
  };
}

function contextFamilies() {
  const families = Object.fromEntries(
    SOURCE_CONTEXT_FAMILIES.map((family) => [family, { status: 'NOT_REPORTED', dimensions: [] }])
  );
  families.BIOLOGICAL = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'crop.identity',
      valueCandidate: 'soybean',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('soybean-specific soil water budget spreadsheet')
    }]
  };
  families.ENVIRONMENTAL = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'site.identity',
      valueCandidate: 'Kellogg Biological Station',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('2015 LTER Agronomic Protocol Kellogg Biological Station')
    }]
  };
  families.MANAGEMENT = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'experiment.identity',
      valueCandidate: 'Resource Gradient Experiment (N-rate Study)',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('Irrigation Scheduling for the Resource Gradient Experiment (N-rate Study)')
    }]
  };
  families.OPERATIONAL = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'decision.domain',
      valueCandidate: 'irrigation scheduling',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('Irrigation Scheduling for the Resource Gradient Experiment (N-rate Study)')
    }]
  };
  families.MEASUREMENT = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'etmax.provenance',
      valueCandidate: 'SALUS 100-year simulation using site-specific historical weather data (1984-2010) and crop-specific T1 data',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('Daily values of ETmax were generated by running a 100 year simulation with the SALUS model')
    }]
  };
  return families;
}

function contextAdjudication() {
  return {
    BIOLOGICAL: [{ semanticId: 'crop.code', valueType: 'CATEGORY' }],
    ENVIRONMENTAL: [{ semanticId: 'site.name', valueType: 'STRING' }],
    MANAGEMENT: [{ semanticId: 'experiment.name', valueType: 'STRING' }],
    OPERATIONAL: [{ semanticId: 'decision.domain', valueType: 'CATEGORY' }],
    MEASUREMENT: [{ semanticId: 'etmax.provenance', valueType: 'STRING' }],
    JURISDICTION_ECONOMIC: []
  };
}

const claimSpecs = [
  ['water-credit', 'RELATIONSHIP', 'In the Resource Gradient Experiment irrigation water budget, rainfall and irrigation amounts are credits to the soil.', 'rainfall and irrigation amounts represent a credit to the soil'],
  ['et-debit', 'RELATIONSHIP', 'In the Resource Gradient Experiment irrigation water budget, evapotranspiration is recorded as a debit to the soil.', 'evapotranspiration (ET) is recorded as a debit to the soil'],
  ['evaluation-start', 'BOUNDARY_CONSTRAINT', 'For the 2015 Resource Gradient Experiment irrigation protocol, daily recording of rainfall and irrigation events starts on May 1.', 'Starting on May 1, LTER staff will record rainfall and irrigation events'],
  ['daily-paw', 'RELATIONSHIP', 'Using recorded rainfall and irrigation inputs together with modeled daily ETmax, the spreadsheet calculates a daily estimate of plant available water in millimeters.', 'the spreadsheet calculates a daily estimate of plant available water (mm)'],
  ['negative-paw-meaning', 'SEMANTIC_DEFINITION', 'Negative plant available water values indicate that soil water is not available for plant uptake.', 'Negative values indicate that soil water is not available for plant uptake'],
  ['two-day-trigger', 'OPERATIONAL_RECOMMENDATION', 'When a negative plant available water value is observed for two consecutive days, an irrigation event is scheduled for the next day.', 'When a negative value is observed for two consecutive days, an irrigation event will be scheduled for the next day'],
  ['rainfall-override', 'BOUNDARY_CONSTRAINT', 'The next-day irrigation schedule is overridden when a rainfall event results in net plant available water.', 'unless there is a rainfall event that results in net plant available water'],
  ['prior-day-deficit-amount', 'RELATIONSHIP', 'The irrigation amount is determined by the plant available water deficit on the day before the scheduled irrigation event.', 'determined by the value of the plant available water deficit on the day prior to the scheduled irrigation event'],
  ['email-coordination', 'OPERATIONAL_RECOMMENDATION', 'Scheduled irrigation events are communicated by e-mail to key investigators and LTER staff.', 'Communication of scheduled irrigation events to key investigators and LTER staff will occur via e-mail'],
  ['email-coordinator', 'OPERATIONAL_RECOMMENDATION', 'Communication of scheduled irrigation events is coordinated by Joe Simmons.', 'will be coordinated by Joe Simmons'],
  ['planning-not-execution', 'BOUNDARY_CONSTRAINT', 'The document is a working protocol for planning purposes; the agronomic field log is the source for actual field operations during 2015.', 'please refer to the agronomic field log for actual field operations that take place during 2015']
].map(([key, claimType, assertion, evidenceText]) => ({ key, claimType, assertion, evidenceText }));

function port(semanticId, epistemicClasses, unit = '1') {
  return {
    semanticId,
    valueType: unit === '1' ? 'BOOLEAN' : 'DECIMAL',
    unit,
    epistemicClasses
  };
}

const env = makeEnv();
env.sourceRegistry = new SourceRegistry({ ledger: env.ledger, artifactStore: new ExactArtifactStore() });
const transcriptBytes = readFileSync(new URL('./kbs-2015-irrigation-page23.txt', import.meta.url));
assert.equal(sourceContentHash(transcriptBytes), EXPECTED_TRANSCRIPTION_HASH);

const source = env.sourceRegistry.registerSource({
  logicalId: 'source.protocol.kbs-2015-rge-irrigation.v2-benchmark',
  version: '1',
  sourceType: 'PROTOCOL',
  title: '2015 LTER Agronomic Protocol — Resource Gradient Experiment irrigation scheduling',
  ownership: OWNERSHIP,
  bibliographic: {
    institution: 'Kellogg Biological Station, Michigan State University',
    program: 'Long-Term Ecological Research (LTER) in Row-Crop Agriculture',
    date: '2015-01-01'
  },
  sourceVersionLabel: '2015',
  originLocator: SOURCE_LOCATOR,
  metadata: { originalPdfPage: PDF_PAGE, benchmarkClass: 'REAL_SOURCE_CURATED_TRANSCRIPTION_V2' },
  audit: audit({ type: 'USER', id: 'kbs-v2-source-curator' }, 'kbs-v2-source')
});

const artifact = env.sourceRegistry.materializeArtifact({
  logicalId: 'artifact.protocol.kbs-2015-rge-irrigation-page23-v2-benchmark',
  version: '1',
  sourceRef: source.ref,
  bytes: transcriptBytes,
  mediaType: 'text/plain; charset=utf-8',
  materializationIdentity: 'kbs-2015-irrigation-page23-whitespace-normalized-transcription-v2-benchmark',
  acquisition: {
    method: 'CURATED_PAGE_TRANSCRIPTION',
    acquiredAt: '2026-08-27T00:30:00.000Z',
    locator: SOURCE_LOCATOR,
    metadata: { originalPdfPage: PDF_PAGE, transcriptionPolicy: 'WHITESPACE_NORMALIZED_NO_SEMANTIC_EDIT' }
  },
  metadata: { originalPdfBytesRetainedByThisBenchmark: false, exactTranscriptionBytesRetained: true },
  audit: audit({ type: 'USER', id: 'kbs-v2-source-curator' }, 'kbs-v2-artifact')
});

const compilerDefinition = createDeterministicCompilerDefinition({
  ledger: env.ledger,
  logicalId: 'compiler.gold.kbs-2015-irrigation.v2',
  version: '1',
  compilerId: 'adr.gold.kbs-2015-irrigation.curated.v2',
  implementationVersion: '1',
  configuration: { sourcePolicy: 'CURATED_SOURCE_FAITHFUL_GOLD_FIXTURE', locatorScheme: 'PDF_PAGE_TEXT_V1' },
  audit: audit({ type: 'SERVICE_ACCOUNT', id: 'gold-protocol-v2-compiler' }, 'kbs-v2-compiler')
});

const compiler = new ScientificCompiler({ ledger: env.ledger, sourceRegistry: env.sourceRegistry });
const compilationBundle = compiler.materializeCompilationProposal({
  compilationLogicalId: 'compilation.gold.kbs-2015-irrigation-source-claims.v2',
  version: '1',
  sourceArtifactRef: artifact.ref,
  compilerDefinitionRef: compilerDefinition.ref,
  proposal: {
    claims: claimSpecs.map((spec) => ({
      key: spec.key,
      claimType: spec.claimType,
      assertion: spec.assertion,
      sourceLocator: locator(spec.evidenceText),
      sourceContext: contextFamilies()
    })),
    runMetadata: { benchmark: 'KBS_2015_IRRIGATION_GOLD_PROTOCOL_V2', curationMode: 'HUMAN_CURATED_ACCEPTANCE_FIXTURE' }
  },
  audit: audit({ type: 'SERVICE_ACCOUNT', id: 'gold-protocol-v2-compiler' }, 'kbs-v2-compilation')
});

const reviewer = createPrincipal({
  principalId: 'gold-kbs-v2-agronomy-reviewer',
  type: 'USER',
  organizationId: OWNERSHIP.organizationId,
  tenantId: OWNERSHIP.tenantId
});
const reviewerRole = publishBuiltinRoleAssignment({
  ledger: env.ledger,
  logicalId: 'role.gold.kbs.v2.agronomy-reviewer',
  version: '1',
  principal: reviewer,
  role: 'AGRONOMY_REVIEWER',
  scope: OWNERSHIP,
  audit: audit({ type: 'USER', id: 'iam-admin' }, 'kbs-v2-reviewer-role')
});
const reviewPolicy = publishKnowledgeGovernancePolicy({
  ledger: env.ledger,
  logicalId: 'policy.gold.kbs.v2.source-review',
  version: '1',
  resourceId: sourceReviewResourceId(source.ref),
  ownership: OWNERSHIP,
  visibilityPolicy: [{ principalId: reviewer.principalId }],
  qualificationScope: [{ use: '*' }],
  deploymentScope: [{ organizationId: OWNERSHIP.organizationId }],
  audit: audit({ type: 'USER', id: 'iam-admin' }, 'kbs-v2-review-policy')
});
const reviewAuthorization = recordAuthorizationDecision({
  ledger: env.ledger,
  decision: authorizeKnowledgeInspection({
    principal: reviewer,
    policy: reviewPolicy,
    roleAssignments: [reviewerRole],
    authorizationScope: OWNERSHIP
  }),
  audit: audit({ type: 'SERVICE_ACCOUNT', id: 'iam-engine' }, 'kbs-v2-review-auth')
});

const sourceFaithful = new SourceFaithfulReviewService({ ledger: env.ledger });
const reviewed = compilationBundle.claimCandidates.map((candidate, index) => {
  const spec = claimSpecs[index];
  return sourceFaithful.reviewCandidate({
    reviewLogicalId: `review.gold.kbs.v2.${spec.key}`,
    reviewVersion: '1',
    compilationResultRef: compilationBundle.result.ref,
    claimCandidateRef: candidate.ref,
    sourceContextCandidateRef: compilationBundle.sourceContextCandidates[index].ref,
    disposition: 'ACCEPT_SOURCE_FAITHFUL',
    contextAdjudication: contextAdjudication(),
    reviewPrincipal: reviewer,
    authorizationDecisionAuditRef: reviewAuthorization.ref,
    claimLogicalId: `claim.gold.kbs.v2.${spec.key}`,
    claimVersion: '1',
    sourceContextLogicalId: `source-context.gold.kbs.v2.${spec.key}`,
    sourceContextVersion: '1',
    audit: audit({ type: reviewer.type, id: reviewer.principalId }, `kbs-v2-source-faithful-${spec.key}`)
  });
});

const scientificApprover = createPrincipal({
  principalId: 'gold-kbs-v2-scientific-approver',
  type: 'USER',
  organizationId: OWNERSHIP.organizationId,
  tenantId: OWNERSHIP.tenantId
});
const scientificApproverRole = publishBuiltinRoleAssignment({
  ledger: env.ledger,
  logicalId: 'role.gold.kbs.v2.scientific-approver',
  version: '1',
  principal: scientificApprover,
  role: 'SCIENTIFIC_APPROVER',
  scope: OWNERSHIP,
  audit: audit({ type: 'USER', id: 'iam-admin' }, 'kbs-v2-scientific-role')
});

const qualificationService = new ScientificQualificationService({ ledger: env.ledger });
const knowledgeByKey = new Map();
for (let index = 0; index < reviewed.length; index += 1) {
  const reviewedItem = reviewed[index];
  const spec = claimSpecs[index];
  const qualificationPolicy = publishKnowledgeGovernancePolicy({
    ledger: env.ledger,
    logicalId: `policy.gold.kbs.v2.qualification.${spec.key}`,
    version: '1',
    resourceId: qualificationResourceId(reviewedItem.claim.ref, reviewedItem.sourceContext.ref),
    ownership: OWNERSHIP,
    visibilityPolicy: [{ principalId: scientificApprover.principalId }],
    qualificationScope: [{ use: '*' }],
    deploymentScope: [{ organizationId: OWNERSHIP.organizationId }],
    audit: audit({ type: 'USER', id: 'iam-admin' }, `kbs-v2-qualification-policy-${spec.key}`)
  });
  const qualificationAuthorization = recordAuthorizationDecision({
    ledger: env.ledger,
    decision: authorizeKnowledgeQualification({
      principal: scientificApprover,
      policy: qualificationPolicy,
      roleAssignments: [scientificApproverRole],
      qualificationTarget: AGRONOMIC_POLICY_REQUIRED_KNOWLEDGE_USE,
      authorizationScope: OWNERSHIP
    }),
    audit: audit({ type: 'SERVICE_ACCOUNT', id: 'iam-engine' }, `kbs-v2-qualification-auth-${spec.key}`)
  });
  const decision = qualificationService.recordQualificationDecision({
    decisionLogicalId: `qualification.gold.kbs.v2.${spec.key}`,
    decisionVersion: '1',
    claimRef: reviewedItem.claim.ref,
    sourceContextRef: reviewedItem.sourceContext.ref,
    disposition: 'QUALIFY_USE',
    qualificationTarget: AGRONOMIC_POLICY_REQUIRED_KNOWLEDGE_USE,
    semanticPreconditions: [
      { semanticId: 'crop.code', operator: 'EQUALS', value: 'soybean' },
      { semanticId: 'experiment.name', operator: 'EQUALS', value: 'Resource Gradient Experiment (N-rate Study)' }
    ],
    approverPrincipal: scientificApprover,
    authorizationDecisionAuditRef: qualificationAuthorization.ref,
    audit: audit({ type: scientificApprover.type, id: scientificApprover.principalId }, `kbs-v2-qualification-${spec.key}`)
  });
  const knowledge = qualificationService.publishQualifiedKnowledge({
    qualifiedKnowledgeLogicalId: `knowledge.gold.kbs.v2.${spec.key}`,
    qualifiedKnowledgeVersion: '1',
    qualificationDecisionRefs: [decision.ref],
    audit: audit({ type: scientificApprover.type, id: scientificApprover.principalId }, `kbs-v2-qualified-${spec.key}`)
  });
  knowledgeByKey.set(spec.key, knowledge);
}

const modelDefinition = {
  type: 'DAILY_SOIL_WATER_BUDGET',
  evaluationCadence: 'P1D',
  credits: ['rainfall_mm', 'irrigation_mm'],
  debits: ['etmax_mm'],
  stateOutput: 'plant_available_water_mm',
  negativeStateMeaning: 'SOIL_WATER_NOT_AVAILABLE_FOR_PLANT_UPTAKE',
  derivedOutputs: ['rainfall_restores_plant_available_water', 'previous_day_plant_available_water_deficit_mm'],
  sourceLimitations: ['THE_PROTOCOL_DOES_NOT_REPORT_THE_FULL_SPREADSHEET_RECURRENCE_OR_INITIAL_STATE']
};
const modelDefinitionHash = agronomicModelDefinitionHash(modelDefinition);

const model = publish(env, 'Model', 'model.gold.kbs-2015-water-budget.v2', '1', modelSpec({
  purpose: 'KBS_2015_RGE_DAILY_PLANT_AVAILABLE_WATER_BUDGET',
  inputs: [port('rainfall_mm', ['OBSERVATION'], 'mm'), port('irrigation_mm', ['OBSERVATION'], 'mm'), port('etmax_mm', ['MODEL_PRIOR'], 'mm')],
  outputs: [
    port('plant_available_water_mm', ['STATE_ESTIMATE'], 'mm'),
    port('rainfall_restores_plant_available_water', ['STATE_ESTIMATE']),
    port('previous_day_plant_available_water_deficit_mm', ['STATE_ESTIMATE'], 'mm')
  ],
  evidenceStateRequirements: ['rainfall_mm', 'irrigation_mm', 'etmax_mm'],
  parameterSlots: [],
  calibrationRequirements: [],
  measurementConventions: ['KBS_2015_PROTOCOL_DAILY_SOIL_WATER_BUDGET'],
  applicabilityDomain: { requiredSemanticIds: ['crop.code', 'experiment.name', 'rainfall_mm', 'irrigation_mm', 'etmax_mm'] },
  limitations: ['KBS_2015_RESOURCE_GRADIENT_EXPERIMENT_PROTOCOL', 'FULL_SPREADSHEET_RECURRENCE_AND_INITIAL_STATE_NOT_REPORTED_BY_SOURCE'],
  computation: { methodId: 'kbs-2015-rge-daily-water-budget-v2-benchmark', definitionHash: modelDefinitionHash }
}));

const rule = {
  contractVersion: AGRONOMIC_RULE_CONTRACT_VERSION_V2,
  ruleId: 'kbs-2015-rge-negative-paw-two-day-irrigation-v2',
  decisionType: 'IRRIGATION_SCHEDULING',
  inputs: ['plant_available_water_mm', 'rainfall_restores_plant_available_water', 'previous_day_plant_available_water_deficit_mm'],
  evaluationCadence: 'P1D',
  evaluationStart: {
    date: '2015-05-01',
    authorityBindings: [{
      role: 'EVALUATION_START_DATE',
      authorityRef: knowledgeByKey.get('evaluation-start').ref,
      rationale: 'The source explicitly starts daily rainfall and irrigation recording on May 1 in the 2015 protocol.'
    }]
  },
  trigger: {
    logic: 'ALL',
    predicates: [{
      semanticId: 'plant_available_water_mm',
      comparator: 'LT',
      value: { type: 'DECIMAL', decimal: '0', unit: 'mm' },
      temporal: { mode: 'CONSECUTIVE', count: 2, period: 'P1D' },
      authorityBindings: [{ role: 'TRIGGER_THRESHOLD_AND_PERSISTENCE', authorityRef: knowledgeByKey.get('two-day-trigger').ref, rationale: 'Two consecutive negative values trigger next-day irrigation.' }]
    }]
  },
  exceptions: [{
    logic: 'ALL',
    predicates: [{
      semanticId: 'rainfall_restores_plant_available_water',
      comparator: 'EQ',
      value: { type: 'BOOLEAN', boolean: true },
      temporal: { mode: 'INSTANT' },
      authorityBindings: [{ role: 'RAINFALL_OVERRIDE', authorityRef: knowledgeByKey.get('rainfall-override').ref, rationale: 'Restorative rainfall overrides the pending irrigation schedule.' }]
    }]
  }],
  action: {
    actionCode: 'IRRIGATE',
    timing: { mode: 'OFFSET', offset: 'P1D' },
    parameters: {
      irrigation_depth_mm: {
        type: 'COPY',
        sourceSemanticId: 'previous_day_plant_available_water_deficit_mm',
        authorityBindings: [{ role: 'ACTION_AMOUNT_BASIS', authorityRef: knowledgeByKey.get('prior-day-deficit-amount').ref, rationale: 'Source says amount is determined by the prior-day deficit.' }]
      }
    },
    authorityBindings: []
  },
  coordination: {
    mode: 'NOTIFY',
    channel: 'EMAIL',
    participants: ['Stacey Vanderwulp', 'Kevin Kahmark', 'Neville Millar', 'Iurii Shcherbak', 'Justin Kunkle', 'Bruno Basso', 'Phil Robertson'],
    coordinator: {
      sourceLabel: 'Joe Simmons',
      authorityBindings: [{
        role: 'COMMUNICATION_COORDINATOR',
        authorityRef: knowledgeByKey.get('email-coordinator').ref,
        rationale: 'The source explicitly states that communication will be coordinated by Joe Simmons.'
      }]
    },
    authorityBindings: [{ role: 'SCHEDULE_COMMUNICATION', authorityRef: knowledgeByKey.get('email-coordination').ref, rationale: 'The source requires e-mail communication to the listed recipients.' }]
  },
  fallback: { disposition: 'WAIT' },
  humanGate: { required: false },
  limitations: ['KBS_2015_RESOURCE_GRADIENT_EXPERIMENT_PROTOCOL', 'WAIT_FALLBACK_IS_ADR_GOVERNANCE_NOT_SOURCE_ASSERTION']
};
const ruleHash = declarativeAgronomicRuleHash(rule);

const policy = publish(env, 'Policy', 'policy.gold.kbs-2015-rge-irrigation.v2', '1', policySpec({
  decisionType: 'IRRIGATION_SCHEDULING',
  actionSpace: ['IRRIGATE', 'WAIT'],
  actionSemantics: {
    equivalenceMode: 'EXACT_MATERIAL_PARAMETERS',
    actions: [
      { actionCode: 'IRRIGATE', parameters: [{ name: 'irrigation_depth_mm', semanticId: 'action.irrigation.amount', valueType: 'DECIMAL', unit: 'mm', required: true, material: true }] },
      { actionCode: 'WAIT', parameters: [] }
    ]
  },
  requiredInputs: [],
  requiredRuntimeOutputs: [
    port('plant_available_water_mm', ['STATE_ESTIMATE'], 'mm'),
    port('rainfall_restores_plant_available_water', ['STATE_ESTIMATE']),
    port('previous_day_plant_available_water_deficit_mm', ['STATE_ESTIMATE'], 'mm')
  ],
  decisionLogic: { methodId: rule.ruleId, definitionHash: ruleHash },
  thresholdAuthority: {
    mode: 'EXTERNAL_AUTHORITY',
    authorityRefs: [knowledgeByKey.get('two-day-trigger').ref, knowledgeByKey.get('rainfall-override').ref, knowledgeByKey.get('prior-day-deficit-amount').ref]
  },
  operationalConstraints: [],
  jurisdictionConstraints: [],
  humanGate: { mode: 'NONE' },
  fallback: { disposition: 'WAIT' },
  abstentionConditions: [],
  limitations: ['KBS_2015_RESOURCE_GRADIENT_EXPERIMENT_PROTOCOL', 'PROTOCOL_IS_PLANNING_AUTHORITY_NOT_EXECUTION_EVIDENCE']
}));
const policyAuthority = validateSpecificationAuthority({ ledger: env.ledger, specificationRef: policy.ref });

const modelKnowledgeBindings = [
  ['WATER_BUDGET_CREDITS', 'water-credit'],
  ['WATER_BUDGET_DEBIT', 'et-debit'],
  ['DAILY_PAW_CALCULATION', 'daily-paw'],
  ['NEGATIVE_PAW_SEMANTICS', 'negative-paw-meaning']
].map(([role, key]) => ({ role, authorityRef: knowledgeByKey.get(key).ref, rationale: `KBS source-faithful authority for ${key}.` }));

const compilationApprover = {
  principalId: manager.principalId,
  type: manager.type,
  organizationId: manager.organizationId,
  tenantId: manager.tenantId
};

const compilation = publishAgronomicPolicyCompilation({
  ledger: env.ledger,
  logicalId: 'agronomic-policy-compilation.gold.kbs-2015-rge-irrigation.v2',
  version: '1',
  compilation: {
    contractVersion: 'adr.agronomic-policy-compilation.v1',
    authorityClass: 'AGRONOMIC_POLICY_COMPILATION_AUTHORITY',
    sourceProtocolRefs: [source.ref],
    sourceProtocolArtifactRefs: [artifact.ref],
    knowledgeRefs: [...knowledgeByKey.values()].map((knowledge) => knowledge.ref),
    modelRefs: [model.ref],
    modelDefinitions: [{
      modelRef: model.ref,
      semanticRole: 'KBS_RGE_PLANT_AVAILABLE_WATER_STATE',
      methodId: model.semanticPayload.computation.methodId,
      inputSemanticIds: ['rainfall_mm', 'irrigation_mm', 'etmax_mm'],
      outputSemanticIds: ['plant_available_water_mm', 'rainfall_restores_plant_available_water', 'previous_day_plant_available_water_deficit_mm'],
      definition: modelDefinition,
      definitionHash: modelDefinitionHash,
      authorityBindings: modelKnowledgeBindings
    }],
    policyRef: policy.ref,
    rule,
    ruleHash,
    transformationRationale: 'The candidate v2 rule preserves the accepted v1 trigger, persistence, exception, action, amount, notification and model semantics while adding source-bound May 1 evaluation start and Joe Simmons coordinator semantics. Protocol planning remains distinct from actual field execution.',
    losslessCoverage: {
      status: 'COMPLETE',
      coveredElements: [
        'ACTION',
        'ACTION_AMOUNT_BASIS',
        'ACTION_TIMING',
        'COORDINATION_CHANNEL_AND_RECIPIENTS',
        'COORDINATION_COORDINATOR',
        'EVALUATION_CADENCE',
        'EVALUATION_START_DATE',
        'EXCEPTION',
        'MODEL_CALCULATION_SEMANTICS',
        'NEGATIVE_STATE_MEANING',
        'PERSISTENCE',
        'PLANNING_EXECUTION_BOUNDARY',
        'SOURCE_ARTIFACT',
        'TRIGGER'
      ],
      unrepresentedElements: []
    },
    approverPrincipal: compilationApprover,
    approvalRef: policyAuthority.managementAuthorization.ref,
    limitations: [
      'CURATED_TRANSCRIPTION_ARTIFACT_NOT_ORIGINAL_PDF_BYTES',
      'ACCEPTANCE_IDENTITIES_ARE_FIXTURE_GOVERNANCE_NOT_EXTERNAL_HUMAN_APPROVAL',
      'PROTOCOL_PLANNING_AUTHORITY_NOT_EXECUTION_EVIDENCE',
      'SOURCE_DOES_NOT_REPORT_FULL_SPREADSHEET_RECURRENCE_OR_INITIAL_STATE'
    ]
  },
  audit: audit({ type: compilationApprover.type, id: compilationApprover.principalId }, 'kbs-v2-gold-protocol-compilation')
});

const validated = validateAgronomicPolicyCompilationAuthority({ ledger: env.ledger, compilationRef: compilation.ref });
assert.equal(validated.semanticPayload.rule.contractVersion, AGRONOMIC_RULE_CONTRACT_VERSION_V2);
assert.equal(validated.semanticPayload.losslessCoverage.status, 'COMPLETE');
assert.deepEqual(validated.semanticPayload.losslessCoverage.unrepresentedElements, []);
assert.equal(validated.semanticPayload.rule.evaluationStart.date, '2015-05-01');
assert.equal(validated.semanticPayload.rule.coordination.coordinator.sourceLabel, 'Joe Simmons');
assert.equal(validated.semanticPayload.rule.trigger.predicates[0].temporal.count, 2);
assert.equal(validated.semanticPayload.rule.action.timing.offset, 'P1D');
assert.equal(validated.semanticPayload.ruleHash, semanticHash('DeclarativeAgronomicRule', validated.semanticPayload.rule));
assert.equal(validated.semanticPayload.modelDefinitions[0].definitionHash, modelDefinitionHash);

for (const knowledge of knowledgeByKey.values()) {
  assert.equal(
    qualificationService.qualifiedUseStatus({ qualifiedKnowledgeRef: knowledge.ref, qualificationTarget: AGRONOMIC_POLICY_REQUIRED_KNOWLEDGE_USE }),
    'QUALIFIED'
  );
  const claim = env.ledger.resolve(knowledge.semanticPayload.claimRef);
  assert.deepEqual(claim.semanticPayload.sourceRef, source.ref);
  assert.deepEqual(claim.semanticPayload.sourceArtifactRef, artifact.ref);
  assert.equal(claim.semanticPayload.sourceLocator.coordinates.page, PDF_PAGE);
}

for (const key of ['evaluation-start', 'email-coordinator']) {
  const ref = knowledgeByKey.get(key).ref;
  assert.ok(validated.semanticPayload.knowledgeRefs.some((candidate) => candidate.semanticHash === ref.semanticHash));
}

const forbiddenRuntimeKinds = new Set(['DecisionResult', 'RuntimeBinding', 'Outcome', 'ExecutionReceipt']);
const runtimeRecords = env.ledger.exportSnapshot().records.filter((record) => forbiddenRuntimeKinds.has(record.ref.kind));
assert.equal(runtimeRecords.length, 0);

console.log(JSON.stringify({
  ok: true,
  benchmark: 'KBS_2015_IRRIGATION_GOLD_PROTOCOL_RULE_V2_CANDIDATE',
  decision: 'DEC-0003_PROPOSED_NOT_NORMATIVE',
  originalPdfPage: PDF_PAGE,
  claimCount: reviewed.length,
  qualifiedKnowledgeCount: knowledgeByKey.size,
  ruleContractVersion: validated.semanticPayload.rule.contractVersion,
  evaluationStart: validated.semanticPayload.rule.evaluationStart,
  coordinator: validated.semanticPayload.rule.coordination.coordinator,
  losslessCoverage: validated.semanticPayload.losslessCoverage,
  sourceModelUnderSpecification: 'FULL_SPREADSHEET_RECURRENCE_AND_INITIAL_STATE_NOT_REPORTED',
  planningNotExecutionBoundaryPreserved: true,
  executionAuthorityRecordsCreated: runtimeRecords.length
}, null, 2));
