import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { semanticHash } from '../../packages/canonicalization/src/index.mjs';
import {
  AGRONOMIC_POLICY_REQUIRED_KNOWLEDGE_USE,
  agronomicModelDefinitionHash,
  declarativeAgronomicRuleHash,
  publishAgronomicPolicyCompilation,
  validateAgronomicPolicyCompilationAuthority
} from '../../packages/agronomic-policy-compilation/src/index.mjs';
import {
  authorizeKnowledgeInspection,
  authorizeKnowledgeQualification,
  createPrincipal,
  publishBuiltinRoleAssignment,
  publishKnowledgeGovernancePolicy,
  recordAuthorizationDecision
} from '../../packages/authorization/src/index.mjs';
import {
  SOURCE_CONTEXT_FAMILIES,
  ScientificCompiler,
  createDeterministicCompilerDefinition
} from '../../packages/scientific-compiler/src/index.mjs';
import {
  ScientificQualificationService,
  qualificationResourceId
} from '../../packages/knowledge-registry/src/qualification.mjs';
import {
  SourceFaithfulReviewService,
  sourceReviewResourceId
} from '../../packages/knowledge-registry/src/source-faithful.mjs';
import {
  ExactArtifactStore,
  SourceRegistry,
  sourceContentHash
} from '../../packages/source-registry/src/index.mjs';
import { validateSpecificationAuthority } from '../../packages/specification-registry/src/index.mjs';
import {
  audit,
  makeEnv,
  manager,
  modelSpec,
  policySpec,
  publish
} from '../specification/fixture.mjs';

const OWNERSHIP = { organizationId: 'org-a', tenantId: 'tenant-a' };
const PDF_PAGE = 23;
const EXPECTED_TRANSCRIPTION_HASH = 'sha256:8d18c0fcc5a2b536d675e9b1cdafc16fbeedb19204b67c11ae81f887844f71d9';
const SOURCE_LOCATOR = 'current_agronomic_protocol.pdf#page=23';

function locator(evidenceText) {
  return {
    kind: 'DOCUMENT_COORDINATE',
    scheme: 'PDF_PAGE_TEXT_V1',
    coordinates: { page: PDF_PAGE, evidenceText }
  };
}

function contextFamilies() {
  const families = Object.fromEntries(
    SOURCE_CONTEXT_FAMILIES.map((family) => [family, { status: 'NOT_REPORTED', dimensions: [] }])
  );
  families.BIOLOGICAL = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'crop.identity',
      valueCandidate: 'soybean',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('soybean-specific soil water budget spreadsheet')
    }]
  };
  families.ENVIRONMENTAL = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'site.identity',
      valueCandidate: 'Kellogg Biological Station',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('2015 LTER Agronomic Protocol Kellogg Biological Station')
    }]
  };
  families.MANAGEMENT = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'experiment.identity',
      valueCandidate: 'Resource Gradient Experiment (N-rate Study)',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('Irrigation Scheduling for the Resource Gradient Experiment (N-rate Study)')
    }]
  };
  families.OPERATIONAL = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'decision.domain',
      valueCandidate: 'irrigation scheduling',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('Irrigation Scheduling for the Resource Gradient Experiment (N-rate Study)')
    }]
  };
  families.MEASUREMENT = {
    status: 'REPORTED',
    dimensions: [{
      semanticHint: 'etmax.provenance',
      valueCandidate: 'SALUS 100-year simulation using site-specific historical weather data (1984-2010) and crop-specific T1 data',
      supportClass: 'EXPLICIT_SOURCE',
      sourceLocator: locator('Daily values of ETmax were generated by running a 100 year simulation with the SALUS model')
    }]
  };
  return families;
}

function contextAdjudication() {
  return {
    BIOLOGICAL: [{ semanticId: 'crop.code', valueType: 'CATEGORY' }],
    ENVIRONMENTAL: [{ semanticId: 'site.name', valueType: 'STRING' }],
    MANAGEMENT: [{ semanticId: 'experiment.name', valueType: 'STRING' }],
    OPERATIONAL: [{ semanticId: 'decision.domain', valueType: 'CATEGORY' }],
    MEASUREMENT: [{ semanticId: 'etmax.provenance', valueType: 'STRING' }],
    JURISDICTION_ECONOMIC: []
  };
}

const claimSpecs = [
  {
    key: 'water-credit',
    claimType: 'RELATIONSHIP',
    assertion: 'In the Resource Gradient Experiment irrigation water budget, rainfall and irrigation amounts are credits to the soil.',
    evidenceText: 'rainfall and irrigation amounts represent a credit to the soil'
  },
  {
    key: 'et-debit',
    claimType: 'RELATIONSHIP',
    assertion: 'In the Resource Gradient Experiment irrigation water budget, evapotranspiration is recorded as a debit to the soil.',
    evidenceText: 'evapotranspiration (ET) is recorded as a debit to the soil'
  },
  {
    key: 'daily-paw',
    claimType: 'RELATIONSHIP',
    assertion: 'Using recorded rainfall and irrigation inputs together with modeled daily ETmax, the spreadsheet calculates a daily estimate of plant available water in millimeters.',
    evidenceText: 'the spreadsheet calculates a daily estimate of plant available water (mm)'
  },
  {
    key: 'negative-paw-meaning',
    claimType: 'SEMANTIC_DEFINITION',
    assertion: 'Negative plant available water values indicate that soil water is not available for plant uptake.',
    evidenceText: 'Negative values indicate that soil water is not available for plant uptake'
  },
  {
    key: 'two-day-trigger',
    claimType: 'OPERATIONAL_RECOMMENDATION',
    assertion: 'When a negative plant available water value is observed for two consecutive days, an irrigation event is scheduled for the next day.',
    evidenceText: 'When a negative value is observed for two consecutive days, an irrigation event will be scheduled for the next day'
  },
  {
    key: 'rainfall-override',
    claimType: 'BOUNDARY_CONSTRAINT',
    assertion: 'The next-day irrigation schedule is overridden when a rainfall event results in net plant available water.',
    evidenceText: 'unless there is a rainfall event that results in net plant available water'
  },
  {
    key: 'prior-day-deficit-amount',
    claimType: 'RELATIONSHIP',
    assertion: 'The irrigation amount is determined by the plant available water deficit on the day before the scheduled irrigation event.',
    evidenceText: 'determined by the value of the plant available water deficit on the day prior to the scheduled irrigation event'
  },
  {
    key: 'email-coordination',
    claimType: 'OPERATIONAL_RECOMMENDATION',
    assertion: 'Scheduled irrigation events are communicated by e-mail to key investigators and LTER staff.',
    evidenceText: 'Communication of scheduled irrigation events to key investigators and LTER staff will occur via e-mail'
  },
  {
    key: 'planning-not-execution',
    claimType: 'BOUNDARY_CONSTRAINT',
    assertion: 'The document is a working protocol for planning purposes; the agronomic field log is the source for actual field operations during 2015.',
    evidenceText: 'please refer to the agronomic field log for actual field operations that take place during 2015'
  }
];

function port(semanticId, epistemicClasses, unit = '1') {
  return {
    semanticId,
    valueType: unit === '1' ? 'BOOLEAN' : 'DECIMAL',
    unit,
    epistemicClasses
  };
}

const env = makeEnv();
env.sourceRegistry = new SourceRegistry({ ledger: env.ledger, artifactStore: new ExactArtifactStore() });

const transcriptBytes = readFileSync(new URL('./kbs-2015-irrigation-page23.txt', import.meta.url));
assert.equal(sourceContentHash(transcriptBytes), EXPECTED_TRANSCRIPTION_HASH);

const source = env.sourceRegistry.registerSource({
  logicalId: 'source.protocol.kbs-2015-rge-irrigation',
  version: '1',
  sourceType: 'PROTOCOL',
  title: '2015 LTER Agronomic Protocol — Resource Gradient Experiment irrigation scheduling',
  ownership: OWNERSHIP,
  bibliographic: {
    institution: 'Kellogg Biological Station, Michigan State University',
    program: 'Long-Term Ecological Research (LTER) in Row-Crop Agriculture',
    date: '2015-01-01'
  },
  sourceVersionLabel: '2015',
  originLocator: SOURCE_LOCATOR,
  metadata: {
    sourceDocument: 'current_agronomic_protocol.pdf',
    originalPdfPage: PDF_PAGE,
    benchmarkClass: 'REAL_SOURCE_CURATED_TRANSCRIPTION'
  },
  audit: audit({ type: 'USER', id: 'kbs-source-curator' }, 'kbs-source')
});

const artifact = env.sourceRegistry.materializeArtifact({
  logicalId: 'artifact.protocol.kbs-2015-rge-irrigation-page23-transcription',
  version: '1',
  sourceRef: source.ref,
  bytes: transcriptBytes,
  mediaType: 'text/plain; charset=utf-8',
  materializationIdentity: 'kbs-2015-irrigation-page23-whitespace-normalized-transcription-v1',
  acquisition: {
    method: 'CURATED_PAGE_TRANSCRIPTION',
    acquiredAt: '2026-08-26T15:30:00.000Z',
    locator: SOURCE_LOCATOR,
    metadata: {
      originalArtifactClass: 'USER_UPLOADED_PDF',
      originalPdfPage: PDF_PAGE,
      transcriptionPolicy: 'WHITESPACE_NORMALIZED_NO_SEMANTIC_EDIT'
    }
  },
  metadata: {
    originalPdfBytesRetainedByThisBenchmark: false,
    exactTranscriptionBytesRetained: true
  },
  audit: audit({ type: 'USER', id: 'kbs-source-curator' }, 'kbs-artifact')
});

const compilerDefinition = createDeterministicCompilerDefinition({
  ledger: env.ledger,
  logicalId: 'compiler.gold.kbs-2015-irrigation',
  version: '1',
  compilerId: 'adr.gold.kbs-2015-irrigation.curated',
  implementationVersion: '1',
  configuration: {
    sourcePolicy: 'CURATED_SOURCE_FAITHFUL_GOLD_FIXTURE',
    locatorScheme: 'PDF_PAGE_TEXT_V1'
  },
  audit: audit({ type: 'SERVICE_ACCOUNT', id: 'gold-protocol-compiler' }, 'kbs-compiler')
});

const compiler = new ScientificCompiler({ ledger: env.ledger, sourceRegistry: env.sourceRegistry });
const compilationBundle = compiler.materializeCompilationProposal({
  compilationLogicalId: 'compilation.gold.kbs-2015-irrigation-source-claims',
  version: '1',
  sourceArtifactRef: artifact.ref,
  compilerDefinitionRef: compilerDefinition.ref,
  proposal: {
    claims: claimSpecs.map((spec) => ({
      key: spec.key,
      claimType: spec.claimType,
      assertion: spec.assertion,
      sourceLocator: locator(spec.evidenceText),
      sourceContext: contextFamilies()
    })),
    runMetadata: {
      benchmark: 'KBS_2015_IRRIGATION_GOLD_PROTOCOL_V1',
      curationMode: 'HUMAN_CURATED_ACCEPTANCE_FIXTURE'
    }
  },
  audit: audit({ type: 'SERVICE_ACCOUNT', id: 'gold-protocol-compiler' }, 'kbs-compilation')
});

const reviewer = createPrincipal({
  principalId: 'gold-kbs-agronomy-reviewer',
  type: 'USER',
  organizationId: OWNERSHIP.organizationId,
  tenantId: OWNERSHIP.tenantId
});
const reviewerRole = publishBuiltinRoleAssignment({
  ledger: env.ledger,
  logicalId: 'role.gold.kbs.agronomy-reviewer',
  version: '1',
  principal: reviewer,
  role: 'AGRONOMY_REVIEWER',
  scope: OWNERSHIP,
  audit: audit({ type: 'USER', id: 'iam-admin' }, 'kbs-reviewer-role')
});
const reviewPolicy = publishKnowledgeGovernancePolicy({
  ledger: env.ledger,
  logicalId: 'policy.gold.kbs.source-review',
  version: '1',
  resourceId: sourceReviewResourceId(source.ref),
  ownership: OWNERSHIP,
  visibilityPolicy: [{ principalId: reviewer.principalId }],
  qualificationScope: [{ use: '*' }],
  deploymentScope: [{ organizationId: OWNERSHIP.organizationId }],
  audit: audit({ type: 'USER', id: 'iam-admin' }, 'kbs-review-policy')
});
const reviewAuthorization = recordAuthorizationDecision({
  ledger: env.ledger,
  decision: authorizeKnowledgeInspection({
    principal: reviewer,
    policy: reviewPolicy,
    roleAssignments: [reviewerRole],
    authorizationScope: OWNERSHIP
  }),
  audit: audit({ type: 'SERVICE_ACCOUNT', id: 'iam-engine' }, 'kbs-review-auth')
});

const sourceFaithful = new SourceFaithfulReviewService({ ledger: env.ledger });
const reviewed = compilationBundle.claimCandidates.map((candidate, index) => {
  const spec = claimSpecs[index];
  return sourceFaithful.reviewCandidate({
    reviewLogicalId: `review.gold.kbs.${spec.key}`,
    reviewVersion: '1',
    compilationResultRef: compilationBundle.result.ref,
    claimCandidateRef: candidate.ref,
    sourceContextCandidateRef: compilationBundle.sourceContextCandidates[index].ref,
    disposition: 'ACCEPT_SOURCE_FAITHFUL',
    contextAdjudication: contextAdjudication(),
    reviewPrincipal: reviewer,
    authorizationDecisionAuditRef: reviewAuthorization.ref,
    claimLogicalId: `claim.gold.kbs.${spec.key}`,
    claimVersion: '1',
    sourceContextLogicalId: `source-context.gold.kbs.${spec.key}`,
    sourceContextVersion: '1',
    audit: audit({ type: reviewer.type, id: reviewer.principalId }, `kbs-source-faithful-${spec.key}`)
  });
});

const scientificApprover = createPrincipal({
  principalId: 'gold-kbs-scientific-approver',
  type: 'USER',
  organizationId: OWNERSHIP.organizationId,
  tenantId: OWNERSHIP.tenantId
});
const scientificApproverRole = publishBuiltinRoleAssignment({
  ledger: env.ledger,
  logicalId: 'role.gold.kbs.scientific-approver',
  version: '1',
  principal: scientificApprover,
  role: 'SCIENTIFIC_APPROVER',
  scope: OWNERSHIP,
  audit: audit({ type: 'USER', id: 'iam-admin' }, 'kbs-scientific-approver-role')
});

const qualificationService = new ScientificQualificationService({ ledger: env.ledger });
const knowledgeByKey = new Map();
for (let index = 0; index < reviewed.length; index += 1) {
  const reviewedItem = reviewed[index];
  const spec = claimSpecs[index];
  const qualificationPolicy = publishKnowledgeGovernancePolicy({
    ledger: env.ledger,
    logicalId: `policy.gold.kbs.qualification.${spec.key}`,
    version: '1',
    resourceId: qualificationResourceId(reviewedItem.claim.ref, reviewedItem.sourceContext.ref),
    ownership: OWNERSHIP,
    visibilityPolicy: [{ principalId: scientificApprover.principalId }],
    qualificationScope: [{ use: '*' }],
    deploymentScope: [{ organizationId: OWNERSHIP.organizationId }],
    audit: audit({ type: 'USER', id: 'iam-admin' }, `kbs-qualification-policy-${spec.key}`)
  });
  const qualificationAuthorization = recordAuthorizationDecision({
    ledger: env.ledger,
    decision: authorizeKnowledgeQualification({
      principal: scientificApprover,
      policy: qualificationPolicy,
      roleAssignments: [scientificApproverRole],
      qualificationTarget: AGRONOMIC_POLICY_REQUIRED_KNOWLEDGE_USE,
      authorizationScope: OWNERSHIP
    }),
    audit: audit({ type: 'SERVICE_ACCOUNT', id: 'iam-engine' }, `kbs-qualification-auth-${spec.key}`)
  });
  const decision = qualificationService.recordQualificationDecision({
    decisionLogicalId: `qualification.gold.kbs.${spec.key}`,
    decisionVersion: '1',
    claimRef: reviewedItem.claim.ref,
    sourceContextRef: reviewedItem.sourceContext.ref,
    disposition: 'QUALIFY_USE',
    qualificationTarget: AGRONOMIC_POLICY_REQUIRED_KNOWLEDGE_USE,
    semanticPreconditions: [
      { semanticId: 'crop.code', operator: 'EQUALS', value: 'soybean' },
      { semanticId: 'experiment.name', operator: 'EQUALS', value: 'Resource Gradient Experiment (N-rate Study)' }
    ],
    approverPrincipal: scientificApprover,
    authorizationDecisionAuditRef: qualificationAuthorization.ref,
    audit: audit({ type: scientificApprover.type, id: scientificApprover.principalId }, `kbs-qualification-${spec.key}`)
  });
  const knowledge = qualificationService.publishQualifiedKnowledge({
    qualifiedKnowledgeLogicalId: `knowledge.gold.kbs.${spec.key}`,
    qualifiedKnowledgeVersion: '1',
    qualificationDecisionRefs: [decision.ref],
    audit: audit({ type: scientificApprover.type, id: scientificApprover.principalId }, `kbs-qualified-${spec.key}`)
  });
  knowledgeByKey.set(spec.key, knowledge);
}

const modelDefinition = {
  type: 'DAILY_SOIL_WATER_BUDGET',
  evaluationCadence: 'P1D',
  credits: ['rainfall_mm', 'irrigation_mm'],
  debits: ['etmax_mm'],
  stateOutput: 'plant_available_water_mm',
  negativeStateMeaning: 'SOIL_WATER_NOT_AVAILABLE_FOR_PLANT_UPTAKE',
  derivedOutputs: [
    'rainfall_restores_plant_available_water',
    'previous_day_plant_available_water_deficit_mm'
  ]
};
const modelDefinitionHash = agronomicModelDefinitionHash(modelDefinition);

const model = publish(env, 'Model', 'model.gold.kbs-2015-water-budget', '1', modelSpec({
  purpose: 'KBS_2015_RGE_DAILY_PLANT_AVAILABLE_WATER_BUDGET',
  inputs: [
    port('rainfall_mm', ['OBSERVATION'], 'mm'),
    port('irrigation_mm', ['OBSERVATION'], 'mm'),
    port('etmax_mm', ['MODEL_PRIOR'], 'mm')
  ],
  outputs: [
    port('plant_available_water_mm', ['STATE_ESTIMATE'], 'mm'),
    port('rainfall_restores_plant_available_water', ['STATE_ESTIMATE']),
    port('previous_day_plant_available_water_deficit_mm', ['STATE_ESTIMATE'], 'mm')
  ],
  evidenceStateRequirements: ['rainfall_mm', 'irrigation_mm', 'etmax_mm'],
  parameterSlots: [],
  calibrationRequirements: [],
  measurementConventions: ['KBS_2015_PROTOCOL_DAILY_SOIL_WATER_BUDGET'],
  applicabilityDomain: {
    requiredSemanticIds: ['crop.code', 'experiment.name', 'rainfall_mm', 'irrigation_mm', 'etmax_mm']
  },
  limitations: [
    'KBS_2015_RESOURCE_GRADIENT_EXPERIMENT_PROTOCOL',
    'MODEL_DEFINITION_REPRESENTS_PROTOCOL_LOGIC_NOT_FIELD_EXECUTION'
  ],
  computation: {
    methodId: 'kbs-2015-rge-daily-water-budget-v1',
    definitionHash: modelDefinitionHash
  }
}));

const rule = {
  contractVersion: 'adr.declarative-agronomic-rule.v1',
  ruleId: 'kbs-2015-rge-negative-paw-two-day-irrigation-v1',
  decisionType: 'IRRIGATION_SCHEDULING',
  inputs: [
    'plant_available_water_mm',
    'rainfall_restores_plant_available_water',
    'previous_day_plant_available_water_deficit_mm'
  ],
  evaluationCadence: 'P1D',
  trigger: {
    logic: 'ALL',
    predicates: [{
      semanticId: 'plant_available_water_mm',
      comparator: 'LT',
      value: { type: 'DECIMAL', decimal: '0', unit: 'mm' },
      temporal: { mode: 'CONSECUTIVE', count: 2, period: 'P1D' },
      authorityBindings: [{
        role: 'TRIGGER_THRESHOLD_AND_PERSISTENCE',
        authorityRef: knowledgeByKey.get('two-day-trigger').ref,
        rationale: 'The source protocol explicitly requires two consecutive negative daily values before scheduling next-day irrigation.'
      }]
    }]
  },
  exceptions: [{
    logic: 'ALL',
    predicates: [{
      semanticId: 'rainfall_restores_plant_available_water',
      comparator: 'EQ',
      value: { type: 'BOOLEAN', boolean: true },
      temporal: { mode: 'INSTANT' },
      authorityBindings: [{
        role: 'RAINFALL_OVERRIDE',
        authorityRef: knowledgeByKey.get('rainfall-override').ref,
        rationale: 'The protocol explicitly makes restorative rainfall an exception to the pending next-day irrigation schedule.'
      }]
    }]
  }],
  action: {
    actionCode: 'IRRIGATE',
    timing: { mode: 'OFFSET', offset: 'P1D' },
    parameters: {
      irrigation_depth_mm: {
        type: 'COPY',
        sourceSemanticId: 'previous_day_plant_available_water_deficit_mm',
        authorityBindings: [{
          role: 'ACTION_AMOUNT_BASIS',
          authorityRef: knowledgeByKey.get('prior-day-deficit-amount').ref,
          rationale: 'The source says amount is determined by the prior-day deficit; direct COPY is an explicit governed operationalization of that wording.'
        }]
      }
    },
    authorityBindings: []
  },
  coordination: {
    mode: 'NOTIFY',
    channel: 'EMAIL',
    participants: ['KEY_INVESTIGATORS', 'LTER_STAFF'],
    authorityBindings: [{
      role: 'SCHEDULE_COMMUNICATION',
      authorityRef: knowledgeByKey.get('email-coordination').ref,
      rationale: 'The protocol explicitly requires e-mail communication of scheduled irrigation events.'
    }]
  },
  fallback: { disposition: 'WAIT' },
  humanGate: { required: false },
  limitations: [
    'KBS_2015_RESOURCE_GRADIENT_EXPERIMENT_PROTOCOL',
    'ACTION_AMOUNT_COPY_IS_GOVERNED_OPERATIONALIZATION_JUDGMENT',
    'WAIT_FALLBACK_IS_ADR_GOVERNANCE_NOT_SOURCE_ASSERTION'
  ]
};
const ruleHash = declarativeAgronomicRuleHash(rule);

const policy = publish(env, 'Policy', 'policy.gold.kbs-2015-rge-irrigation', '1', policySpec({
  decisionType: 'IRRIGATION_SCHEDULING',
  actionSpace: ['IRRIGATE', 'WAIT'],
  actionSemantics: {
    equivalenceMode: 'EXACT_MATERIAL_PARAMETERS',
    actions: [
      {
        actionCode: 'IRRIGATE',
        parameters: [{
          name: 'irrigation_depth_mm',
          semanticId: 'action.irrigation.amount',
          valueType: 'DECIMAL',
          unit: 'mm',
          required: true,
          material: true
        }]
      },
      { actionCode: 'WAIT', parameters: [] }
    ]
  },
  requiredInputs: [],
  requiredRuntimeOutputs: [
    port('plant_available_water_mm', ['STATE_ESTIMATE'], 'mm'),
    port('rainfall_restores_plant_available_water', ['STATE_ESTIMATE']),
    port('previous_day_plant_available_water_deficit_mm', ['STATE_ESTIMATE'], 'mm')
  ],
  decisionLogic: { methodId: rule.ruleId, definitionHash: ruleHash },
  thresholdAuthority: {
    mode: 'EXTERNAL_AUTHORITY',
    authorityRefs: [
      knowledgeByKey.get('two-day-trigger').ref,
      knowledgeByKey.get('rainfall-override').ref,
      knowledgeByKey.get('prior-day-deficit-amount').ref
    ]
  },
  operationalConstraints: [],
  jurisdictionConstraints: [],
  humanGate: { mode: 'NONE' },
  fallback: { disposition: 'WAIT' },
  abstentionConditions: [],
  limitations: [
    'KBS_2015_RESOURCE_GRADIENT_EXPERIMENT_PROTOCOL',
    'PROTOCOL_IS_PLANNING_AUTHORITY_NOT_EXECUTION_EVIDENCE'
  ]
}));

const policyAuthority = validateSpecificationAuthority({ ledger: env.ledger, specificationRef: policy.ref });
const compilationApprover = {
  principalId: manager.principalId,
  type: manager.type,
  organizationId: manager.organizationId,
  tenantId: manager.tenantId
};

const modelKnowledgeBindings = [
  ['WATER_BUDGET_CREDITS', 'water-credit'],
  ['WATER_BUDGET_DEBIT', 'et-debit'],
  ['DAILY_PAW_CALCULATION', 'daily-paw'],
  ['NEGATIVE_PAW_SEMANTICS', 'negative-paw-meaning']
].map(([role, key]) => ({
  role,
  authorityRef: knowledgeByKey.get(key).ref,
  rationale: `KBS source-faithful authority for ${key}.`
}));

const compilation = publishAgronomicPolicyCompilation({
  ledger: env.ledger,
  logicalId: 'agronomic-policy-compilation.gold.kbs-2015-rge-irrigation',
  version: '1',
  compilation: {
    contractVersion: 'adr.agronomic-policy-compilation.v1',
    authorityClass: 'AGRONOMIC_POLICY_COMPILATION_AUTHORITY',
    sourceProtocolRefs: [source.ref],
    sourceProtocolArtifactRefs: [artifact.ref],
    knowledgeRefs: [...knowledgeByKey.values()].map((knowledge) => knowledge.ref),
    modelRefs: [model.ref],
    modelDefinitions: [{
      modelRef: model.ref,
      semanticRole: 'KBS_RGE_PLANT_AVAILABLE_WATER_STATE',
      methodId: model.semanticPayload.computation.methodId,
      inputSemanticIds: ['rainfall_mm', 'irrigation_mm', 'etmax_mm'],
      outputSemanticIds: [
        'plant_available_water_mm',
        'rainfall_restores_plant_available_water',
        'previous_day_plant_available_water_deficit_mm'
      ],
      definition: modelDefinition,
      definitionHash: modelDefinitionHash,
      authorityBindings: modelKnowledgeBindings
    }],
    policyRef: policy.ref,
    rule,
    ruleHash,
    transformationRationale: [
      'The KBS protocol page is represented as a source-faithful curated transcription artifact anchored to original PDF page 23.',
      'Source assertions are independently published as QualifiedKnowledge for AGRONOMIC_POLICY_INPUT before operationalization.',
      'Water-budget semantics remain Model authority; trigger, exception, action timing, amount basis and coordination remain Policy authority.',
      'COPY of prior-day deficit and WAIT fallback are explicit ADR operationalization judgments and are not laundered into source claims.',
      'The source itself says the protocol is for planning and that actual operations must be checked in the agronomic field log.'
    ].join(' '),
    losslessCoverage: {
      status: 'COMPLETE',
      coveredElements: [
        'ACTION',
        'ACTION_AMOUNT_BASIS',
        'ACTION_TIMING',
        'COORDINATION',
        'EVALUATION_CADENCE',
        'EXCEPTION',
        'MODEL_CALCULATION',
        'NEGATIVE_STATE_MEANING',
        'PERSISTENCE',
        'PLANNING_EXECUTION_BOUNDARY',
        'SOURCE_ARTIFACT',
        'TRIGGER'
      ],
      unrepresentedElements: []
    },
    approverPrincipal: compilationApprover,
    approvalRef: policyAuthority.managementAuthorization.ref,
    limitations: [
      'CURATED_TRANSCRIPTION_ARTIFACT_NOT_ORIGINAL_PDF_BYTES',
      'ACCEPTANCE_IDENTITIES_ARE_FIXTURE_GOVERNANCE_NOT_EXTERNAL_HUMAN_APPROVAL',
      'PROTOCOL_PLANNING_AUTHORITY_NOT_EXECUTION_EVIDENCE'
    ]
  },
  audit: audit({ type: compilationApprover.type, id: compilationApprover.principalId }, 'kbs-gold-protocol-compilation')
});

const validated = validateAgronomicPolicyCompilationAuthority({
  ledger: env.ledger,
  compilationRef: compilation.ref
});

assert.equal(validated.semanticPayload.losslessCoverage.status, 'COMPLETE');
assert.equal(validated.semanticPayload.sourceProtocolRefs[0].logicalId, source.ref.logicalId);
assert.equal(validated.semanticPayload.sourceProtocolArtifactRefs[0].logicalId, artifact.ref.logicalId);
assert.equal(validated.semanticPayload.rule.trigger.predicates[0].temporal.count, 2);
assert.equal(validated.semanticPayload.rule.action.timing.offset, 'P1D');
assert.equal(validated.semanticPayload.rule.coordination.mode, 'NOTIFY');
assert.equal(validated.semanticPayload.ruleHash, semanticHash('DeclarativeAgronomicRule', validated.semanticPayload.rule));
assert.equal(validated.semanticPayload.modelDefinitions[0].definitionHash, modelDefinitionHash);

for (const knowledge of knowledgeByKey.values()) {
  assert.equal(
    qualificationService.qualifiedUseStatus({
      qualifiedKnowledgeRef: knowledge.ref,
      qualificationTarget: AGRONOMIC_POLICY_REQUIRED_KNOWLEDGE_USE
    }),
    'QUALIFIED'
  );
  const claim = env.ledger.resolve(knowledge.semanticPayload.claimRef);
  assert.deepEqual(claim.semanticPayload.sourceRef, source.ref);
  assert.deepEqual(claim.semanticPayload.sourceArtifactRef, artifact.ref);
  assert.equal(claim.semanticPayload.sourceLocator.coordinates.page, PDF_PAGE);
}

const planningKnowledge = knowledgeByKey.get('planning-not-execution');
assert.ok(validated.semanticPayload.knowledgeRefs.some((ref) => ref.semanticHash === planningKnowledge.ref.semanticHash));
const forbiddenRuntimeKinds = new Set(['DecisionResult', 'RuntimeBinding', 'Outcome', 'ExecutionReceipt']);
const runtimeRecords = env.ledger.exportSnapshot().records.filter((record) => forbiddenRuntimeKinds.has(record.ref.kind));
assert.equal(runtimeRecords.length, 0, 'gold protocol compilation must not manufacture execution or outcome authority');

console.log(JSON.stringify({
  ok: true,
  benchmark: 'KBS_2015_IRRIGATION_GOLD_PROTOCOL_V1',
  sourceRef: source.ref,
  sourceArtifactRef: artifact.ref,
  sourceArtifactContentHash: artifact.semanticPayload.contentHash,
  sourceArtifactClass: 'CURATED_PAGE_TRANSCRIPTION',
  originalPdfBytesRetainedByBenchmark: false,
  originalPdfPage: PDF_PAGE,
  claimCount: reviewed.length,
  qualifiedKnowledgeCount: knowledgeByKey.size,
  requiredScientificUse: AGRONOMIC_POLICY_REQUIRED_KNOWLEDGE_USE,
  modelRef: model.ref,
  policyRef: policy.ref,
  compilationRef: compilation.ref,
  ruleHash,
  modelDefinitionHash,
  losslessCoverage: validated.semanticPayload.losslessCoverage,
  planningNotExecutionBoundaryPreserved: true,
  executionAuthorityRecordsCreated: runtimeRecords.length
}, null, 2));
